[package]
name = "snapshot-proc-macro"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6"

[dependencies.syn]
version = "0.14"
features = ["parsing", "printing", "full", "extra-traits", "clone-impls" ]
